
export const indianAirports = [
    { code: "DEL", name: "Indira Gandhi International Airport", city: "Delhi" },
    { code: "BOM", name: "Chhatrapati Shivaji Maharaj International Airport", city: "Mumbai" },
    { code: "BLR", name: "Kempegowda International Airport", city: "Bengaluru" },
    { code: "MAA", name: "Chennai International Airport", city: "Chennai" },
    { code: "CCU", name: "Netaji Subhas Chandra Bose International Airport", city: "Kolkata" },
    { code: "HYD", name: "Rajiv Gandhi International Airport", city: "Hyderabad" },
    { code: "GOI", name: "Dabolim Airport", city: "Goa" },
    { code: "PNQ", name: "Pune International Airport", city: "Pune" },
    { code: "AMD", name: "Sardar Vallabhbhai Patel International Airport", city: "Ahmedabad" },
    { code: "COK", name: "Cochin International Airport", city: "Kochi" },
    { code: "JAI", name: "Jaipur International Airport", city: "Jaipur" },
    { code: "LKO", name: "Chaudhary Charan Singh International Airport", city: "Lucknow" },
    { code: "TRV", name: "Trivandrum International Airport", city: "Thiruvananthapuram" },
    { code: "IXC", name: "Shaheed Bhagat Singh International Airport", city: "Chandigarh" },
    { code: "BBI", name: "Biju Patnaik International Airport", city: "Bhubaneswar" },
    { code: "NAG", name: "Dr. Babasaheb Ambedkar International Airport", city: "Nagpur" },
    { code: "PAT", name: "Jay Prakash Narayan International Airport", city: "Patna" },
    { code: "VNS", name: "Lal Bahadur Shastri International Airport", city: "Varanasi" },
    { code: "IXB", name: "Bagdogra International Airport", city: "Siliguri" },
    { code: "SXR", name: "Sheikh ul-Alam International Airport", city: "Srinagar" },
    { code: "GAU", name: "Lokpriya Gopinath Bordoloi International Airport", city: "Guwahati" },
    { code: "IXZ", name: "Veer Savarkar International Airport", city: "Port Blair" },
    { code: "IMF", name: "Bir Tikendrajit International Airport", city: "Imphal" },
    { code: "IXR", name: "Birsa Munda International Airport", city: "Ranchi" },
    { code: "RPR", name: "Swami Vivekananda Airport", city: "Raipur" },
    { code: "DIB", name: "Dibrugarh Airport", city: "Dibrugarh" },
    { code: "IXM", name: "Madurai International Airport", city: "Madurai" },
    { code: "TIR", name: "Tirupati Airport", city: "Tirupati" },
    { code: "IXE", name: "Mangalore International Airport", city: "Mangalore" },
    { code: "STV", name: "Surat Airport", city: "Surat" },
    { code: "BDQ", name: "Vadodara Airport", city: "Vadodara" },
    { code: "BHO", name: "Raja Bhoj Airport", city: "Bhopal" },
    { code: "IXJ", name: "Jammu Airport", city: "Jammu" },
    { code: "ATQ", name: "Sri Guru Ram Dass Jee International Airport", city: "Amritsar" },
    { code: "IXL", name: "Kushok Bakula Rimpochee Airport", city: "Leh" },
    { code: "DED", name: "Jolly Grant Airport", city: "Dehradun" },
    { code: "UDR", name: "Maharana Pratap Airport", city: "Udaipur" },
    { code: "IXA", name: "Maharaja Bir Bikram Airport", city: "Agartala" },
    { code: "AJL", name: "Lengpui Airport", city: "Aizawl" },
    { code: "DMU", name: "Dimapur Airport", city: "Dimapur" },
    { code: "IXI", name: "Lilabari Airport", city: "North Lakhimpur" },
    { code: "SHL", name: "Shillong Airport", city: "Shillong" },
    { code: "DHM", name: "Gaggal Airport", city: "Dharamshala" },
    { code: "IXD", name: "Prayagraj Airport", city: "Prayagraj" },
    { code: "GWL", name: "Rajmata Vijaya Raje Scindia Airport", city: "Gwalior" },
    { code: "JRH", name: "Jorhat Airport", city: "Jorhat" },
    { code: "IXU", name: "Aurangabad Airport", city: "Aurangabad" },
    { code: "TCR", name: "Tuticorin Airport", city: "Thoothukudi" },
    { code: "VGA", name: "Vijayawada International Airport", city: "Vijayawada" },
    { code: "CDP", name: "Kadapa Airport", city: "Kadapa" },
    { code: "HBX", name: "Hubli Airport", city: "Hubli" },
    { code: "IXY", name: "Kandla Airport", city: "Kandla" },
    { code: "JSA", name: "Jaisalmer Airport", city: "Jaisalmer" },
    { code: "BHU", name: "Bhavnagar Airport", city: "Bhavnagar" },
    { code: "JGA", name: "Jamnagar Airport", city: "Jamnagar" },
    { code: "RAJ", name: "Rajkot Airport", city: "Rajkot" },
    { code: "IDR", name: "Devi Ahilya Bai Holkar Airport", city: "Indore" },
    { code: "IXG", name: "Belgaum Airport", city: "Belgaum" },
    { code: "TRZ", name: "Tiruchirapalli International Airport", city: "Tiruchirapalli" },
];
